#!/bin/bash

# Quiz Simulation Demo Script
# This script demonstrates how to run the quiz simulation

echo "========================================================================="
echo "🎮 Quiz Terminal Simulation - Demo"
echo "========================================================================="
echo ""
echo "This demo will show you how to run the quiz admin and user terminals."
echo ""
echo "STEPS:"
echo "------"
echo ""
echo "1. Open Terminal 1 and run the ADMIN:"
echo "   $ bun run admin"
echo ""
echo "2. Note the ACTIVITY KEY displayed (e.g., quiz-a1b2c3d4)"
echo ""
echo "3. Open Terminal 2 and run USER 1:"
echo "   $ bun run user <activity-key> Alice"
echo ""
echo "4. Open Terminal 3 and run USER 2:"
echo "   $ bun run user <activity-key> Bob"
echo ""
echo "5. Open Terminal 4 and run USER 3:"
echo "   $ bun run user <activity-key> Charlie"
echo ""
echo "6. In ADMIN terminal, select option 1 to start the quiz"
echo ""
echo "7. Watch the quiz flow in all terminals!"
echo ""
echo "========================================================================="
echo ""
echo "QUICK START EXAMPLE:"
echo "--------------------"
echo ""
echo "Step 1 - Start Admin (run this in one terminal):"
echo "  bun run admin"
echo ""
echo "Step 2 - Start Users (run these in separate terminals):"
echo '  bun run user $(cat .activity-key 2>/dev/null || echo "quiz-a1b2c3d4") Alice'
echo '  bun run user $(cat .activity-key 2>/dev/null || echo "quiz-a1b2c3d4") Bob'
echo '  bun run user $(cat .activity-key 2>/dev/null || echo "quiz-a1b2c3d4") Charlie'
echo ""
echo "========================================================================="
echo ""
echo "ADMIN MENU OPTIONS:"
echo "-------------------"
echo "1. Start Quiz"
echo "2. Show Connected Users"
echo "3. Show Leaderboard"
echo "4. Show Current Question Stats"
echo "5. Show Questions List"
echo "6. Set Question Interval (5-60 seconds)"
echo "7. Show Activity Info"
echo "8. End Quiz"
echo "0. Exit"
echo ""
echo "========================================================================="
echo ""
echo "USER EXPERIENCE:"
echo "----------------"
echo "- Join lobby with nickname"
echo "- Wait for admin to start quiz"
echo "- Answer questions by typing option number (1-4)"
echo "- See live statistics after answering"
echo "- View leaderboard after each question"
echo "- See final results at the end"
echo ""
echo "========================================================================="
echo ""
echo "For more details, see README.md"
echo ""
